# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
permalink:        /blog/:title

# Setup
title:            Joe Kampschmidt's Code
description:      "a pragmatic approach to web and software development"
url:              http://www.jokecamp.com
baseurl:          /

author:
  name:           'Joe Kampschmidt'
  url:            https://twitter.com/jokecamp
  email:          joe.kampschmidt@gmail.com

githubProject:    https://github.com/jokecamp/jokecamp.com/
githubBranch:     tree/master/

# Custom vars
github:           https://github.com/jokecamp
twitter:          https://twitter.com/jokecamp
stackoverflow:    http://stackoverflow.com/users/215502/kampsj
